[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RACHEL"
authors = [{name = "World Possible", email = "james@worldpossible.org"}]
dynamic = ["version", "description"]
